[package]
name = "axum_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
axum = { version = "0.8.4" }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = { version = "1.0.145" }
dotenvy = "0.15.7"
